version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/var/www/flapper_bingo
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      MAIN_API: http://localhost:8080
    command: start
